language: scala
sudo: required
scala:
 - 2.11.12
 - 2.12.8
jdk:
 - openjdk8
matrix:
  include:
  - scala: 2.13.0
    script:
    - travis_wait 60 sbt ++$TRAVIS_SCALA_VERSION test
cache:
  directories:
   - "$HOME/.ivy2/cache"
   - "$HOME/.sbt/boot/"
script:
 - travis_wait 60 sbt ++$TRAVIS_SCALA_VERSION validate
after_success:
 - bash <(curl -s https://codecov.io/bash)
